apiVersion: v1
kind: PersistentVolume
metadata:
 name: vol1
spec:
 capacity:
  storage: 1Gi
 volumeMode: Filesystem
 accessModes:
  - ReadWriteMany
 persistentVolumeReclaimPolicy: Delete
 storageClassName: ""
 hostPath:
    path: /tmp/my-pv
~                     
