 echo -n "postgres" |  base64
cG9zdGdyZXM=
====================================================
apiVersion: v1
kind: Secret
metadata:
 name: secret
data:
 POSTGRES_USER: cG9zdGdyZXM=
 POSTGRES_PASSWORD: cG9zdGdyZXM=
